---
title: "High Performance Project 1 Analysis"
output: html_notebook
---

```{r}
chunk1M16c.out <- read.csv("../exp_data/chunk1M16c.out", header = FALSE)
chunk1M16cDyn.out <- read.csv("../exp_data/chunk1M16cDyn.out", header = FALSE)
chunk1M4cstatic.out <- read.csv("../exp_data/chunk1M4cstatic.out", header = FALSE)
chunk1M4cstaticb.out <- read.csv("../exp_data/chunk1M4cstaticb.out", header = FALSE)
para1M16cstaticdynamic.out <- read.csv("../exp_data/para1M16cstaticdynamic.out", header = FALSE)
para1m12c.out <- read.csv("../exp_data/para1m12c.out", header = FALSE)
para1m16c.out <- read.csv("../exp_data/para1m16c.out", header = FALSE)
para1m16cb.out <- read.csv("../exp_data/para1m16cb.out", header = FALSE)
para1m16cdyn.out <- read.csv("../exp_data/para1m16cdyn.out", header = FALSE)
para1m2c.out <- read.csv("../exp_data/para1m2c.out", header = FALSE)
para1m2cb.out <- read.csv("../exp_data/para1m2cb.out", header = FALSE)
para1m4c.out <- read.csv("../exp_data/para1m4c.out", header = FALSE)
para1m8c.out <- read.csv("../exp_data/para1m8c.out", header = FALSE)
seq1m.out <- read.csv("../exp_data/seq1m.out", header = FALSE)
testseq.out <- read.csv("../exp_data/testseq.out", header = FALSE)
```

```{r}
seq1m.out <- cbind(seq1m.out, V9 = NA)
para <- rbind(para1m2c.out, para1m2cb.out, para1m4c.out, seq1m.out, para1m8c.out, para1m16c.out, para1m16cb.out, para1m12c.out)
para <- para[complete.cases(para$V4), ]
para$V2 <- factor(para$V2)
```

```{r}
library(ggplot2)
ggplot(data = para) + geom_boxplot(aes(x = V6, y = V2, group = V2)) + coord_flip() + xlab("Elapsed time") + ylab("Number of Threads")
ggplot(data = para) + geom_boxplot(aes(x = V5, y = V2, group = V2)) + coord_flip() + xlab("CPU cycles") + ylab("Number of Threads")
```

```{r}
library(dplyr)
unfactor <- function(v) {
  as.numeric(as.character(v))
}
medians <- group_by(para, V2) %>% summarise(across(c(V5, V6), median))
threads <- unfactor(medians$V2)
ggplot() + geom_line(aes(x = threads, y = medians$V6), color = "blue") + geom_point(aes(x = threads, y = medians$V6), color = "blue")
ggplot() + geom_line(aes(x = threads, y = medians$V5/(threads*medians$V6)), color = "blue") + geom_line(aes(x = threads, y = 1), color = "red")
```

```{r}
sort_atomic_crit <- read.csv("../sort_and_atomic_critical_analysis/results-19-09-23/combined.csv",  header = FALSE)
sort_atomic_crit <- sort_atomic_crit[complete.cases(sort_atomic_crit$V5),]
sort_atomic_crit$V2 <- as.integer(sort_atomic_crit$V2)
```

```{r}
seq_i <- 1:nrow(sort_atomic_crit)
ggplot(sort_atomic_crit) + geom_point(aes(x = seq_i, y = V5/(V2*V6)))
```

```{r}
sort_atomic_crit$TYPE <- NA
sort_atomic_crit$TYPE <- ifelse(sort_atomic_crit$V2 == 1 & sort_atomic_crit$V10 == "NORMAL", "Reduction", sort_atomic_crit$TYPE)
sort_atomic_crit$TYPE <- ifelse(sort_atomic_crit$V2 == 1 & sort_atomic_crit$V10 == "SORT", "Sort", sort_atomic_crit$TYPE)
sort_atomic_crit$TYPE <- ifelse(sort_atomic_crit$V11 == "REDUCTION" & sort_atomic_crit$V10 == "REDUCTION", "Reduction", sort_atomic_crit$TYPE)
sort_atomic_crit$TYPE <- ifelse(sort_atomic_crit$V11 == "CRITICAL" & sort_atomic_crit$V10 == "CRITICAL", "Critical", sort_atomic_crit$TYPE)
sort_atomic_crit$TYPE <- ifelse(sort_atomic_crit$V11 == "REDUCTION" & sort_atomic_crit$V10 == "SORT", "Sort", sort_atomic_crit$TYPE)
sort_atomic_crit$TYPE <- ifelse(sort_atomic_crit$V11 == "ATOMIC" & sort_atomic_crit$V10 == "REDUCTION", "Atomic", sort_atomic_crit$TYPE)
sort_atomic_crit
```

```{r}
sac_sub <- subset(sort_atomic_crit, V2 < 50)
src_elapsed_medians <- sac_sub %>% group_by(across(all_of(c("V2", "TYPE")))) %>% summarise(elapsed_med = median(V6), elapsed_CF = median(CF))
ggplot() + geom_jitter(data = sac_sub, aes(x = V2, y = V6, color = TYPE)) + xlab("Number of Threads") + ylab("Elapsed Time") + geom_path(data = src_elapsed_medians, aes(x = V2, y = elapsed_med, color = TYPE))
ggsave("sac_elapsed.png")
```

```{r}
sort_atomic_crit$CF <- sort_atomic_crit$V5/(sort_atomic_crit$V6*sort_atomic_crit$V2)
ggplot() + geom_jitter(data = sac_sub, aes(x = V2, y = CF, color = TYPE)) + xlab("Number of Threads") + geom_path(data = src_elapsed_medians, aes(x = V2, y = elapsed_CF, color = TYPE))
ggsave("sac_cf.png")
```

```{r}
seq_normal_med <- subset(src_elapsed_medians, TYPE == "Reduction" & V2 == 1)$elapsed_med
seq_sort_med <- subset(src_elapsed_medians, TYPE == "Sort" & V2 == 1)$elapsed_med
sac_sub$SEQ_MED <- ifelse(sac_sub$TYPE == "Sort", seq_sort_med, seq_normal_med)
sac_sub$SUF <- sac_sub$SEQ_MED/sac_sub$V6
SUF_trends <- sac_sub %>% group_by(across(all_of(c("V2", "TYPE")))) %>% summarise(SUF = median(SUF))
ggplot() + geom_jitter(data = sac_sub, aes(x = V2, y = SUF, color = TYPE)) + geom_line(aes(x=c(0,32), y = c(0,32)), color = "red") + xlab("Number of Threads") + geom_path(data = SUF_trends, aes(x = V2, y = SUF, color = TYPE))
ggsave("sac_suf.png")
```

```{r}
threads_analysis <- read.csv("../exp_data/new_thread_exps/combined.csv", header = FALSE)
threads_analysis
```

```{r}
format_as_latex_table <- function(df) {
  str <- paste(paste(names(df), collapse = " & "), "\n\\hline\\hline\n", collapse = "")
  for (i in 1:nrow(df)) {
    str <- paste(str, paste(df[i,], collapse = " & "), "\n\\hline\n", collapse = "")
  }
  cat(str)
}
```

```{r}
time.means <- colMeans(threads_analysis[,5:8]) 
time.sds <- apply(threads_analysis[,5:8], 2, sd)
time.combined <- data.frame(Method = c("clock", "omp_get_wtime", "POSIX clock montonic", "POSIX Process CPU time"), Mean = time.means, SD = time.sds)
format_as_latex_table(time.combined)
```
```{r}
ggplot(threads_analysis) + geom_point(aes(x = V2, y = V5, color = "cpu cycles")) + geom_point(aes(x = V2, y = V6, color = "elapsed time")) + xlab("Number of Threads") + ylab("Seconds")
ggsave("timing_compare.png")
```


```{r}
threads_analysis$clock_factor <- threads_analysis$V5/(threads_analysis$V2 * threads_analysis$V6)
ggplot(threads_analysis) + geom_point(aes(x = V2, y = V5/(V2*V6))) + xlab("Number of Threads") + ylab("CF")
ggsave("threads_clock_ratio.png")
```


```{r}
subset(threads_analysis, V2 == 64)
```

```{r}
seq_median <- median(subset(threads_analysis, V2 == 1)$V6)
ggplot() + geom_point(data = threads_analysis, aes(x = V2, y = seq_median/V6)) + geom_line(aes(x=c(0,64), y = c(0,64)), color = "red") + xlab("Number of Threads") + ylab("SUF")
ggsave("threads_speed_up_plot.png")
```







# fishes

```{r}
fishes <- read.csv("../exp_data/fishes/combined.csv", header = FALSE)
fishes$`Number of Threads` <- factor(fishes$V2)
fishes$CF <- fishes$V5/(fishes$V2*fishes$V6)
```

```{r}
ggplot() + geom_jitter(data = fishes, aes(x = V3, y = V6, color = `Number of Threads`)) + scale_x_log10() + xlab("Fishes") + ylab("Elapsed Time")
ggsave("fishes_elapsed.png")
```


```{r}
ggplot() + geom_jitter(data = fishes, aes(x = V3, y = CF, color = `Number of Threads`)) + scale_x_log10() + xlab("Fishes")
ggsave("fishes_cf.png")
```

```{r}
fishes_medians <- fishes %>% group_by(across(all_of(c("Number of Threads", "V3")))) %>% summarise(elapsed_medium = median(V6))
fishes_med_sub <- subset(fishes_medians, V3 != 1000000)
fishes_t1 <- subset(fishes_med_sub, `Number of Threads` == 1)
fishes_t4 <- subset(fishes_med_sub, `Number of Threads` == 4)
combined <- cbind(fishes_t1, fishes_t4)
SUF <- combined$elapsed_medium...3/combined$elapsed_medium...6
fishes_x <- fishes_t1$V3
ggplot() + geom_jitter(aes(x = fishes_x, y = SUF)) + scale_x_log10() + xlab("Fishes") + geom_hline(yintercept = 4, color = "red")
ggsave("fishes_suf.png")
```

